# Generated by Django 3.1.4 on 2020-12-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpin', models.CharField(max_length=4)),
                ('accno', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
